import React, { Component, PropTypes } from 'react';

import Paper from 'material-ui/Paper';
<<<<<<< b92d05d3c3db46ac84a856f8d8e26e9867ad9176
import { mixpanelURLTrack } from 'middlewares/mixpanelTrackers';
import lightBaseTheme from 'material-ui/styles/baseThemes/lightBaseTheme';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';
=======
>>>>>>> company

import styles from 'css/components/privacy';
import classNames from 'classnames/bind';
const cx = classNames.bind(styles);

<<<<<<< b92d05d3c3db46ac84a856f8d8e26e9867ad9176
class Privacy extends Component {

  componentDidMount() {
    mixpanelURLTrack('PRIVACY[load]:init');
  }
  
  render() {
    return (
      <MuiThemeProvider muiTheme={getMuiTheme(lightBaseTheme)}>
      <div className={cx('legal') + ' container'}>
        <Paper className={cx('paper')} zDepth={2} >
          <h1><strong>Uiba Privacy Summary</strong></h1>
          <ul>
            <li><strong><strong>Your Trust is of the Utmost Importance To Us, and We Will Never Betray It</strong></strong></li>
          </ul>
          <ul>
            <li><strong>Your Personal Data and Your Professional Data are </strong><strong><em>Yours</em></strong></li>
          </ul>
          <ul>
            <li><strong>Your Data is </strong><strong><em>Private</em></strong></li>
          </ul>
          <ul>
            <li><strong>Your Data is </strong><strong><em>Protected</em></strong></li>
          </ul>
          <ul>
            <li><strong>Your Data is </strong><strong><em>Portable</em></strong></li>
          </ul>
          <ul>
            <li><strong>Your Trust is of the Utmost Importance To Us, and We Will Never Betray It</strong></li>
          </ul>
          <p><span>You have chosen to trust us with your Personal data and your Professional data. We understand what a significant responsibility that is, and we promise to never do anything to let you down or betray your trust.</span></p>
          <p><span>Our business is </span><strong>NOT</strong><span> in selling this Personal data or Professional data. We simply don&rsquo;t do that.</span></p>
          <p><span>Our business </span><strong>IS</strong><span> in providing you a safe, secure place to plan and manage your professional career.</span></p>
          <ul>
            <li><strong><strong>Your Personal Data and Your Professional Data are </strong><strong><em>Yours</em></strong></strong></li>
          </ul>
          <p><span>You are in control of your Personal data and your Professional data. You can decide what information is available to third parties or opt out of sharing it with third parties entirely.</span></p>
          <ul>
            <li><strong><strong>Your Data is </strong><strong><em>Private</em></strong></strong></li>
          </ul>
          <p><span>Personal data contains sensitive information like email addresses, phone numbers, and notes. We consider your personal data to be privileged information and we will never sell, rent or lease your personal data. You control who has access to it.</span></p>
          <p><span>To provide and improve elements of the Uiba service (for example, building more accurate career recommendations) we may need to store and process this data behind the scenes. However, your personal data is not disclosed to any other Uiba user without your explicit permission.</span></p>
          <p><span>Uiba has features that allow you to publish and share some of your professional data with others, but these features are completely optional and whether or not you use them is up to you. If you choose to connect your Uiba account with one of our development partners, you may be giving the partner access to your professional data. We will tell you how the partner application will access your account and you can turn off access whenever you want.</span></p>
          <ul>
            <li><strong><strong>Your Data is </strong><strong><em>Protected</em></strong></strong></li>
          </ul>
          <p><span>We will always strive to keep your data safe and secure. We take many precautions to protect your data from accidental loss and theft. We don&rsquo;t store your Uiba account password on our servers and no one at Uiba will ever ask you for it.</span></p>
          <ul>
            <li><strong><strong>Your Data is </strong><strong><em>Portable</em></strong></strong></li>
          </ul>
          <p><span>Our business model is not predicated on locking you into a proprietary service that you can never escape. We believe strongly that your data should be portable and usable anywhere. We will always provide you the ability to export your data from our systems at any time using industry standard formats.</span></p>
          <p><strong><strong><br /><br /></strong></strong></p>
          <p><strong>Uiba </strong><strong><br /></strong><strong>Privacy Policy | Your Privacy Rights </strong></p>
          <p><span>Uiba Inc. (&ldquo;</span><strong>Uiba</strong><span>&ldquo;) is committed to protecting your privacy. We have prepared this Privacy Policy to describe to you our practices regarding the Personal Data (as defined below) we collect from users of (a) our website located at Uiba.com, (&ldquo;</span><strong>Site</strong><span>&ldquo;) (b) our Services, including the Uiba Apps and API, and (c) Developer Apps. Capitalized terms not defined in this Privacy Policy have the meanings given in our Terms of Use located at </span><span>www.Uiba.com/terms.</span></p>
=======
const Privacy = () => {
  return (
    <div className={cx('legal') + ' container'}>
      <Paper className={cx('paper')} zDepth={2} >
        <h1><strong>Uiba Privacy Summary</strong></h1>
        <ul>
          <li><strong><strong>Your Trust is of the Utmost Importance To Us, and We Will Never Betray It</strong></strong></li>
        </ul>
        <ul>
          <li><strong>Your Personal Data and Your Professional Data are </strong><strong><em>Yours</em></strong></li>
        </ul>
        <ul>
          <li><strong>Your Data is </strong><strong><em>Private</em></strong></li>
        </ul>
        <ul>
          <li><strong>Your Data is </strong><strong><em>Protected</em></strong></li>
        </ul>
        <ul>
          <li><strong>Your Data is </strong><strong><em>Portable</em></strong></li>
        </ul>
        <ul>
          <li><strong>Your Trust is of the Utmost Importance To Us, and We Will Never Betray It</strong></li>
        </ul>
        <p><span>You have chosen to trust us with your Personal data and your Professional data. We understand what a significant responsibility that is, and we promise to never do anything to let you down or betray your trust.</span></p>
        <p><span>Our business is </span><strong>NOT</strong><span> in selling this Personal data or Professional data. We simply don&rsquo;t do that.</span></p>
        <p><span>Our business </span><strong>IS</strong><span> in providing you a safe, secure place to plan and manage your professional career.</span></p>
        <ul>
          <li><strong><strong>Your Personal Data and Your Professional Data are </strong><strong><em>Yours</em></strong></strong></li>
        </ul>
        <p><span>You are in control of your Personal data and your Professional data. You can decide what information is available to third parties or opt out of sharing it with third parties entirely.</span></p>
        <ul>
          <li><strong><strong>Your Data is </strong><strong><em>Private</em></strong></strong></li>
        </ul>
        <p><span>Personal data contains sensitive information like email addresses, phone numbers, and notes. We consider your personal data to be privileged information and we will never sell, rent or lease your personal data. You control who has access to it.</span></p>
        <p><span>To provide and improve elements of the Uiba service (for example, building more accurate career recommendations) we may need to store and process this data behind the scenes. However, your personal data is not disclosed to any other Uiba user without your explicit permission.</span></p>
        <p><span>Uiba has features that allow you to publish and share some of your professional data with others, but these features are completely optional and whether or not you use them is up to you. If you choose to connect your Uiba account with one of our development partners, you may be giving the partner access to your professional data. We will tell you how the partner application will access your account and you can turn off access whenever you want.</span></p>
        <ul>
          <li><strong><strong>Your Data is </strong><strong><em>Protected</em></strong></strong></li>
        </ul>
        <p><span>We will always strive to keep your data safe and secure. We take many precautions to protect your data from accidental loss and theft. We don&rsquo;t store your Uiba account password on our servers and no one at Uiba will ever ask you for it.</span></p>
        <ul>
          <li><strong><strong>Your Data is </strong><strong><em>Portable</em></strong></strong></li>
        </ul>
        <p><span>Our business model is not predicated on locking you into a proprietary service that you can never escape. We believe strongly that your data should be portable and usable anywhere. We will always provide you the ability to export your data from our systems at any time using industry standard formats.</span></p>
        <p><strong><strong><br /><br /></strong></strong></p>
        <p><strong>Uiba </strong><strong><br /></strong><strong>Privacy Policy | Your Privacy Rights </strong></p>
        <p><span>Uiba Inc. (&ldquo;</span><strong>Uiba</strong><span>&ldquo;) is committed to protecting your privacy. We have prepared this Privacy Policy to describe to you our practices regarding the Personal Data (as defined below) we collect from users of (a) our website located at Uiba.com, (&ldquo;</span><strong>Site</strong><span>&ldquo;) (b) our Services, including the Uiba Apps and API, and (c) Developer Apps. Capitalized terms not defined in this Privacy Policy have the meanings given in our Terms of Use located at </span><span>www.Uiba.com/terms.</span></p>
        <ol className={cx('ordered-list')}>
          <li><strong>User Consent.</strong><span> By submitting Personal Data through (a) our Site or Services, including the Uiba App or API, or (b) Developer Apps, you agree to the terms of this Privacy Policy, you expressly consent to the collection, use and disclosure of your Personal Data in accordance with this Privacy Policy, and you represent and warrant that you have all rights necessary to submit such Personal Data. </span></li>
          <li><strong>A Note about Children.</strong><span> We do not intentionally gather Personal Data from visitors who are under the age of 13. </span></li>
          <li><strong>A Note to Users Outside of the United States.</strong><span> Your Personal Data may be processed in the country in which it was collected and in other countries, including the United States, where laws regarding processing of Personal Data may be less stringent than the laws in your country. We adhere to the United States / European Union Privacy Shield Arrangement, which can be located at </span><a href="https://www.privacyshield.gov"><span>https://www.privacyshield.gov/</span></a><span>. </span></li>
          <li><strong>Types of Data We Collect. &ldquo;Personal Data&rdquo;</strong><span> means data that allows someone to identify or contact you including, for example, your name, telephone number, e-mail address, as well as any other non-public information about you that is associated with or linked to any of the foregoing data. &ldquo;</span><strong>Anonymous Data</strong><span>&rdquo; means data that is not associated with or linked to your Personal Data; Anonymous Data does not, by itself, permit the identification of individual persons. We collect Personal Data and Anonymous Data, as described below. </span></li>
          <ol className={cx('ordered-list')}>
            <li><strong>Information You Provide to Us.</strong></li>
            <ul>
              <li><span>We may collect Personal Data from you, such as your first and last name, e-mail addresses, professional title, company name, school name, degree, and password when you create an account. </span></li>
              <li><span>When you order Services on our Site, we (or our third party service provider) will collect all information necessary to complete the transaction, including your name, credit card information, billing information and shipping information. </span></li>
              <li><span>If you provide us feedback or contact us via e-mail, we will collect your name and e-mail address, as well as any other content included in the e-mail, in order to send you a reply. </span></li>
              <li><span>When you participate in one of our surveys, we may collect additional profile information </span></li>
              <li><span>We may also collect Personal Data, such as at other points in our Site that state that Personal Data is being collected. </span></li>
            </ul>
            <li><strong>Information Collected via Technology.</strong></li>
            <ul>
              <li><span>To make our Site and Services more useful to you, our servers (which may be hosted by a third party service provider) collect information from you, including your browser type, operating system, Internet Protocol (IP) address (a number that is automatically assigned to your computer when you use the Internet, which may vary from session to session), domain name, and/or a date/time stamp for your visit. </span></li>
              <li><span>We also use cookies and URL information to gather information regarding the date and time of your visit and the information for which you searched and which you viewed. &ldquo;</span><strong>Cookies</strong><span>&rdquo; are small pieces of information that a website sends to your computer&rsquo;s hard drive while you are viewing a web site. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them) to provide you with a more personal and interactive experience on our Site. Persistent Cookies can be removed by following Internet browser help file directions. </span></li>
              <li><span>We may collect, and we allow third parties to collect, information about how you use and interact with our Site and Services. For example, we use Google Analytics. </span></li>
            </ul>
            <li><strong>Information Collected via Uiba Apps and Developer Apps.</strong><span> When you use a Uiba App or Developer App, the app will collect End User Contact Data. &ldquo;</span><strong>End User Contact Data</strong><span>&rdquo; means information about you that includes first name, last name, birth date, age, email address, gender, company, job title, photos, website urls, social network handles, instant messenger handles, physical address (but does not include any information that you provide when you register for any of our Sites or Services or Developer Apps)(collectively, &ldquo;</span><strong>End User Contact Data</strong><span>&rdquo;). </span></li>
            <li><strong>Information Collected Through Your Email Service.</strong><span> We make available a feature for certain email services or email software whereby our systems will collect End User Contact Data from your email. This is a feature that you must choose to activate via the Uiba App or your account, and you may choose to deactivate this feature at any time. When this feature is activated, your email is copied to our servers and automatically scanned for contact information (i.e., End User Contact Data). The copy of the email is automatically deleted promptly after the scan. We use IMAP (Internet Message Access Protocol) for accessing email from your email provider (e.g., Gmail). IMAP is an Internet standard protocol used by email clients to retrieve email messages from a mail server over a TCP/IP connection. For some email services, you may need to provide your username and password for us to access your email to enable this feature. We use industry-standard security practices for the security of your username and password. </span></li>
            <li><strong>Information Collected from Third Parties.</strong><span> We may collect information about you and other individuals (including those in your End User Contact Data) from the following third party sources: (a) third parties who license, sell or otherwise provide data they have collected; or (b) information from publicly available sources, such as via the Internet and social networks, including through public or licensed APIs (&ldquo;</span><strong>Public Data</strong><span>&rdquo;). We do not collect data from webpages that have been designated (in a standards-based way) as private. </span></li>
            <li><strong>How We Combine Data.</strong><span> We will not process your End User Contact Data for purposes of cookie tracking, ad exchanges, ad networks, or sending electronic communications (including email). We may, however, combine your End User Contact Data with Public Data to create more complete data records (&ldquo;</span><strong>Completed Contact Data</strong><span>&rdquo;). When we do this, we separate data into two different groups: data elements, such as an actual email address, or social media user name, and data associations, which are the links we make between different data elements to assign multiple data elements to the same person. We do not sell your End User Contact Information or disclose your End User Contact Information to any third party; provided, however that we may use your End User Contact Information to make data associations between data elements (provided the data elements constitute Public Data) and disclose these data elements as Completed Contact Data even if the data association was previously undisclosed. For example, if a person has a twitter handle, an email address and a facebook page, all of which constitute Public Data, and you provide End User Contact Data that includes the data association to tie those three elements of Public Data together, we can disclose that connection. Further, nothing shall restrict our right to use, access, process, collect, disclose, share or distribute any Public Data, even if such Public Data is duplicative of your End User Contact Data. </span></li>
          </ol>
          <li><strong>Use of Your Personal Data</strong></li>
          <ol className={cx('ordered-list')}>
            <li><strong>End User Contact Data and Completed Contact Data.</strong><span> We use End User Contact Data and Completed Contact Data as described above. </span></li>
            <li><strong>General Use.</strong><span> In general, Personal Data you submit to us is used either to respond to requests that you make, or to aid us in serving you better. We use your Personal Data in the following ways: </span></li>
            <ul>
              <li><span>facilitate the creation of and secure your account on our network; </span></li>
              <li><span>identify you as a user in our system; </span></li>
              <li><span>provide improved administration and quality of experience of our Site and Services; </span></li>
              <li><span>provide the Services you request; </span></li>
              <li><span>send you a welcome e-mail to verify ownership of the e-mail address provided when your account was created; </span></li>
              <li><span>send you administrative e-mail notifications, such as security or support and maintenance advisories; </span></li>
              <li><span>meet legal and regulatory requirements;</span></li>
              <li><span>respond to your inquiries related to employment opportunities or other requests; and </span></li>
              <li><span>send newsletters, surveys, offers, and other promotional materials related to our Services and for other marketing purposes of Uiba. </span></li>
            </ul>
            <li><strong>Creation of Anonymous Data.</strong><span> We may create Anonymous Data records from Personal Data by excluding information (such as your name) that makes the data personally identifiable to you. We use this Anonymous Data to analyze request and usage patterns so that we may enhance the content of our Services and improve Site navigation. Uiba reserves the right to use Anonymous Data for any purpose and disclose Anonymous Data to third parties in its sole discretion. </span></li>
          </ol>
          <li><strong>Disclosure of Your Personal Data.</strong><span> We disclose your Personal Data, End User Contact Data and Completed Contact Data as described below and as described elsewhere in this Privacy Policy. </span></li>
          <ol className={cx('ordered-list')}>
            <li><strong>Third Party Service Providers.</strong><span> We may share your Personal Data with third party service providers to: provide you with the Services that we offer you through our Site; to conduct quality assurance testing; to facilitate creation of accounts; to provide technical support; and/or to provide other services to Uiba. These third party service providers are required not to use your Personal Data other than to provide the services requested by Uiba. Uiba requires its service providers to whom it discloses Personal Data and who are not subject to the laws based on the EU Data Protection Directive 95/46 or Swiss Federal Data Protection law to either (i) subscribe to the Privacy Shield principles or (ii) contractually agree to provide at least the same level of protection for Personal Data as is required by the relevant Privacy Shield principles. </span></li>
            <li><strong>Affiliates and Acquisitions.</strong><span> We may share some or all of your Personal Data with our subsidiaries, joint ventures, or other companies under a common control (&ldquo;Affiliates&rdquo;), in which case we will require our Affiliates to honor this Privacy Policy. If another company acquires our company, business, or our assets, that company will possess the Personal Data collected by us and will assume the rights and obligations regarding your Personal Data as described in this Privacy Policy. </span></li>
            <li><strong>Other Disclosures.</strong><span> Regardless of any choices you make regarding your Personal Data (as described below), Uiba may disclose Personal Data if it believes in good faith that such disclosure is necessary (a) in connection with any legal investigation; (b) to comply with relevant laws or to respond to subpoenas or warrants served on Uiba; (c) to protect or defend the rights or property of Uiba or users of the Services; and/or (d) to investigate or assist in preventing any violation or potential violation of the law, this Privacy Policy, or Terms of Use. </span></li>
            <li><strong>Developers.</strong><span> Developers may want access to Personal Data (including End User Contact Data) that we collect from their customers. As a result, we may provide your Personal Data to Developers; however (and in accordance with California&rsquo;s &ldquo;Shine the Light&rdquo; Act codified at Civil Code section 1798.83), we will cease any further disclosure of your Personal Data to Developers for their own direct marketing purposes if you &ldquo;opt-out&rdquo; by contacting us as described in Section 13 below. If you wish to discontinue receipt of these e-mails, please contact the applicable Developer directly to update your preferences. The privacy policies of the Developers may apply to the use and disclosure of your Personal Data that we collect and disclose to such Developers. We contractually require Developers to not, and to require their customers to not, use such data for the purposes of cookie tracking, ad exchanges, ad networks, data brokerages, and sending electronic communications (including email) in violation of applicable law. Uiba requires Developers to whom it discloses Personal Data and who are not subject to the laws based on the EU Data Protection Directive 95/46 or Swiss Federal Data Protection law to either (i) subscribe to the Privacy Shield principles or (ii) contractually agree to provide at least the same level of protection for Personal Data as is required by the relevant Privacy Shield principles. </span></li>
          </ol>
          <li><strong>Third Party Websites.</strong><span> When you click on a link to any other website or location, you will leave our Site and go to another site and another entity may collect Personal Data or Anonymous Data from you. We have no control over, do not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites or content, or to any collection of data after you click on links to such outside websites. </span></li>
          <li><strong>Your Choices Regarding Your Personal Data</strong></li>
          <ol className={cx('ordered-list')}>
            <li><strong>Email Choices.</strong><span> We offer you choices regarding the collection, use, and sharing of your Personal Data. If you are a registered user (including a Developer or a person who has claimed his profile), we will periodically send you free newsletters and e-mails that promote our Site or Services as well as products or services we think you may be interested in. When you receive such promotional newsletters or communications from us, you may indicate a preference to stop receiving them from us and you will have the opportunity to &ldquo;opt-out&rdquo; by following the unsubscribe instructions provided in the e-mail you receive or by contacting us directly. Despite your indicated e-mail preferences, we may send you service related communication, including notices of any updates to our Terms of Use or Privacy Policy. </span></li>
            <li><strong>Access, Correction, and Deletion.</strong><span> Uiba allows individuals to access, modify, and set permissions with respect to End User Contact Data that it holds about them. For example, Uiba also provides certain features that allow you to publish and share some of your Personal Data, End User Contact Data or Completed Contact Data with others, but these features are totally optional and whether or not you use them is up to you. If you choose to connect your Uiba account with one of our development partners, you may be giving the partner access to your Personal Data, End User Contact Data or Completed Contact Data. We will tell you how the partner application will access your account and you can turn off access whenever you want. Finally, Uiba provides you with the ability to export your Personal Data, End User Contact Data or Completed Contact Data from our systems at any time using industry standard formats. </span></li>
            <li><strong>Additional Choices For California Residents &ndash; Your California Privacy Rights (As Provided by California Civil Code section 1798.83).</strong><span> California&rsquo;s &ldquo;Shine the Light&rdquo; law, Civil Code section 1798.83, requires certain businesses that share customer personal information with third parties for the third parties&rsquo; direct marketing purposes to respond to requests from California customers asking about the businesses&rsquo; practices related to such information-sharing. Alternately, such businesses may have in place a policy not to disclose a customer&rsquo;s personal information to third parties for the third parties&rsquo; direct marketing purposes if the customer has exercised an option to opt-out of such information-sharing. We have such a policy in place. As described in Section 8(2) above, you can opt-out of our sharing of your personal information with third parties for the third parties&rsquo; direct marketing purposes by claiming your profile and selecting how your personal information is used. To find out more about your opt-out rights, please contact us at the address listed in Section 13 below. Please note that under California law businesses are only required to respond to a customer making such a request once during any calendar year. </span></li>
          </ol>
          <li><strong>Data Integrity.</strong><span> Uiba will use Personal Data only in ways that are compatible with the purposes for which it was collected or subsequently authorized by you. Uiba will take reasonable steps to ensure that Personal Data is relevant to its intended use, accurate, complete, and current. Uiba depends on you to update and correct your Personal Data to the extent necessary for the purposes for which it was collected and subsequently authorized by you. </span></li>
          <li><strong>Enforcement.</strong><span> Uiba conducts periodic self-assessments to verify that the attestations and assertions it makes about its privacy practices are true and that such privacy practices have been implemented as presented. Uiba will take steps to remedy any problems arising out of failure to comply with the Privacy Shield principles. </span></li>
          <li><strong>Disputes.</strong></li>
>>>>>>> company
          <ol className={cx('ordered-list')}>
            <li><strong>User Consent.</strong><span> By submitting Personal Data through (a) our Site or Services, including the Uiba App or API, or (b) Developer Apps, you agree to the terms of this Privacy Policy, you expressly consent to the collection, use and disclosure of your Personal Data in accordance with this Privacy Policy, and you represent and warrant that you have all rights necessary to submit such Personal Data. </span></li>
            <li><strong>A Note about Children.</strong><span> We do not intentionally gather Personal Data from visitors who are under the age of 13. </span></li>
            <li><strong>A Note to Users Outside of the United States.</strong><span> Your Personal Data may be processed in the country in which it was collected and in other countries, including the United States, where laws regarding processing of Personal Data may be less stringent than the laws in your country. We adhere to the United States / European Union Privacy Shield Arrangement, which can be located at </span><a href="https://www.privacyshield.gov"><span>https://www.privacyshield.gov/</span></a><span>. </span></li>
            <li><strong>Types of Data We Collect. &ldquo;Personal Data&rdquo;</strong><span> means data that allows someone to identify or contact you including, for example, your name, telephone number, e-mail address, as well as any other non-public information about you that is associated with or linked to any of the foregoing data. &ldquo;</span><strong>Anonymous Data</strong><span>&rdquo; means data that is not associated with or linked to your Personal Data; Anonymous Data does not, by itself, permit the identification of individual persons. We collect Personal Data and Anonymous Data, as described below. </span></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Information You Provide to Us.</strong></li>
              <ul>
                <li><span>We may collect Personal Data from you, such as your first and last name, e-mail addresses, professional title, company name, school name, degree, and password when you create an account. </span></li>
                <li><span>When you order Services on our Site, we (or our third party service provider) will collect all information necessary to complete the transaction, including your name, credit card information, billing information and shipping information. </span></li>
                <li><span>If you provide us feedback or contact us via e-mail, we will collect your name and e-mail address, as well as any other content included in the e-mail, in order to send you a reply. </span></li>
                <li><span>When you participate in one of our surveys, we may collect additional profile information </span></li>
                <li><span>We may also collect Personal Data, such as at other points in our Site that state that Personal Data is being collected. </span></li>
              </ul>
              <li><strong>Information Collected via Technology.</strong></li>
              <ul>
                <li><span>To make our Site and Services more useful to you, our servers (which may be hosted by a third party service provider) collect information from you, including your browser type, operating system, Internet Protocol (IP) address (a number that is automatically assigned to your computer when you use the Internet, which may vary from session to session), domain name, and/or a date/time stamp for your visit. </span></li>
                <li><span>We also use cookies and URL information to gather information regarding the date and time of your visit and the information for which you searched and which you viewed. &ldquo;</span><strong>Cookies</strong><span>&rdquo; are small pieces of information that a website sends to your computer&rsquo;s hard drive while you are viewing a web site. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them) to provide you with a more personal and interactive experience on our Site. Persistent Cookies can be removed by following Internet browser help file directions. </span></li>
                <li><span>We may collect, and we allow third parties to collect, information about how you use and interact with our Site and Services. For example, we use Google Analytics. </span></li>
              </ul>
              <li><strong>Information Collected via Uiba Apps and Developer Apps.</strong><span> When you use a Uiba App or Developer App, the app will collect End User Contact Data. &ldquo;</span><strong>End User Contact Data</strong><span>&rdquo; means information about you that includes first name, last name, birth date, age, email address, gender, company, job title, photos, website urls, social network handles, instant messenger handles, physical address (but does not include any information that you provide when you register for any of our Sites or Services or Developer Apps)(collectively, &ldquo;</span><strong>End User Contact Data</strong><span>&rdquo;). </span></li>
              <li><strong>Information Collected Through Your Email Service.</strong><span> We make available a feature for certain email services or email software whereby our systems will collect End User Contact Data from your email. This is a feature that you must choose to activate via the Uiba App or your account, and you may choose to deactivate this feature at any time. When this feature is activated, your email is copied to our servers and automatically scanned for contact information (i.e., End User Contact Data). The copy of the email is automatically deleted promptly after the scan. We use IMAP (Internet Message Access Protocol) for accessing email from your email provider (e.g., Gmail). IMAP is an Internet standard protocol used by email clients to retrieve email messages from a mail server over a TCP/IP connection. For some email services, you may need to provide your username and password for us to access your email to enable this feature. We use industry-standard security practices for the security of your username and password. </span></li>
              <li><strong>Information Collected from Third Parties.</strong><span> We may collect information about you and other individuals (including those in your End User Contact Data) from the following third party sources: (a) third parties who license, sell or otherwise provide data they have collected; or (b) information from publicly available sources, such as via the Internet and social networks, including through public or licensed APIs (&ldquo;</span><strong>Public Data</strong><span>&rdquo;). We do not collect data from webpages that have been designated (in a standards-based way) as private. </span></li>
              <li><strong>How We Combine Data.</strong><span> We will not process your End User Contact Data for purposes of cookie tracking, ad exchanges, ad networks, or sending electronic communications (including email). We may, however, combine your End User Contact Data with Public Data to create more complete data records (&ldquo;</span><strong>Completed Contact Data</strong><span>&rdquo;). When we do this, we separate data into two different groups: data elements, such as an actual email address, or social media user name, and data associations, which are the links we make between different data elements to assign multiple data elements to the same person. We do not sell your End User Contact Information or disclose your End User Contact Information to any third party; provided, however that we may use your End User Contact Information to make data associations between data elements (provided the data elements constitute Public Data) and disclose these data elements as Completed Contact Data even if the data association was previously undisclosed. For example, if a person has a twitter handle, an email address and a facebook page, all of which constitute Public Data, and you provide End User Contact Data that includes the data association to tie those three elements of Public Data together, we can disclose that connection. Further, nothing shall restrict our right to use, access, process, collect, disclose, share or distribute any Public Data, even if such Public Data is duplicative of your End User Contact Data. </span></li>
            </ol>
            <li><strong>Use of Your Personal Data</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>End User Contact Data and Completed Contact Data.</strong><span> We use End User Contact Data and Completed Contact Data as described above. </span></li>
              <li><strong>General Use.</strong><span> In general, Personal Data you submit to us is used either to respond to requests that you make, or to aid us in serving you better. We use your Personal Data in the following ways: </span></li>
              <ul>
                <li><span>facilitate the creation of and secure your account on our network; </span></li>
                <li><span>identify you as a user in our system; </span></li>
                <li><span>provide improved administration and quality of experience of our Site and Services; </span></li>
                <li><span>provide the Services you request; </span></li>
                <li><span>send you a welcome e-mail to verify ownership of the e-mail address provided when your account was created; </span></li>
                <li><span>send you administrative e-mail notifications, such as security or support and maintenance advisories; </span></li>
                <li><span>meet legal and regulatory requirements;</span></li>
                <li><span>respond to your inquiries related to employment opportunities or other requests; and </span></li>
                <li><span>send newsletters, surveys, offers, and other promotional materials related to our Services and for other marketing purposes of Uiba. </span></li>
              </ul>
              <li><strong>Creation of Anonymous Data.</strong><span> We may create Anonymous Data records from Personal Data by excluding information (such as your name) that makes the data personally identifiable to you. We use this Anonymous Data to analyze request and usage patterns so that we may enhance the content of our Services and improve Site navigation. Uiba reserves the right to use Anonymous Data for any purpose and disclose Anonymous Data to third parties in its sole discretion. </span></li>
            </ol>
            <li><strong>Disclosure of Your Personal Data.</strong><span> We disclose your Personal Data, End User Contact Data and Completed Contact Data as described below and as described elsewhere in this Privacy Policy. </span></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Third Party Service Providers.</strong><span> We may share your Personal Data with third party service providers to: provide you with the Services that we offer you through our Site; to conduct quality assurance testing; to facilitate creation of accounts; to provide technical support; and/or to provide other services to Uiba. These third party service providers are required not to use your Personal Data other than to provide the services requested by Uiba. Uiba requires its service providers to whom it discloses Personal Data and who are not subject to the laws based on the EU Data Protection Directive 95/46 or Swiss Federal Data Protection law to either (i) subscribe to the Privacy Shield principles or (ii) contractually agree to provide at least the same level of protection for Personal Data as is required by the relevant Privacy Shield principles. </span></li>
              <li><strong>Affiliates and Acquisitions.</strong><span> We may share some or all of your Personal Data with our subsidiaries, joint ventures, or other companies under a common control (&ldquo;Affiliates&rdquo;), in which case we will require our Affiliates to honor this Privacy Policy. If another company acquires our company, business, or our assets, that company will possess the Personal Data collected by us and will assume the rights and obligations regarding your Personal Data as described in this Privacy Policy. </span></li>
              <li><strong>Other Disclosures.</strong><span> Regardless of any choices you make regarding your Personal Data (as described below), Uiba may disclose Personal Data if it believes in good faith that such disclosure is necessary (a) in connection with any legal investigation; (b) to comply with relevant laws or to respond to subpoenas or warrants served on Uiba; (c) to protect or defend the rights or property of Uiba or users of the Services; and/or (d) to investigate or assist in preventing any violation or potential violation of the law, this Privacy Policy, or Terms of Use. </span></li>
              <li><strong>Developers.</strong><span> Developers may want access to Personal Data (including End User Contact Data) that we collect from their customers. As a result, we may provide your Personal Data to Developers; however (and in accordance with California&rsquo;s &ldquo;Shine the Light&rdquo; Act codified at Civil Code section 1798.83), we will cease any further disclosure of your Personal Data to Developers for their own direct marketing purposes if you &ldquo;opt-out&rdquo; by contacting us as described in Section 13 below. If you wish to discontinue receipt of these e-mails, please contact the applicable Developer directly to update your preferences. The privacy policies of the Developers may apply to the use and disclosure of your Personal Data that we collect and disclose to such Developers. We contractually require Developers to not, and to require their customers to not, use such data for the purposes of cookie tracking, ad exchanges, ad networks, data brokerages, and sending electronic communications (including email) in violation of applicable law. Uiba requires Developers to whom it discloses Personal Data and who are not subject to the laws based on the EU Data Protection Directive 95/46 or Swiss Federal Data Protection law to either (i) subscribe to the Privacy Shield principles or (ii) contractually agree to provide at least the same level of protection for Personal Data as is required by the relevant Privacy Shield principles. </span></li>
            </ol>
            <li><strong>Third Party Websites.</strong><span> When you click on a link to any other website or location, you will leave our Site and go to another site and another entity may collect Personal Data or Anonymous Data from you. We have no control over, do not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites or content, or to any collection of data after you click on links to such outside websites. </span></li>
            <li><strong>Your Choices Regarding Your Personal Data</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Email Choices.</strong><span> We offer you choices regarding the collection, use, and sharing of your Personal Data. If you are a registered user (including a Developer or a person who has claimed his profile), we will periodically send you free newsletters and e-mails that promote our Site or Services as well as products or services we think you may be interested in. When you receive such promotional newsletters or communications from us, you may indicate a preference to stop receiving them from us and you will have the opportunity to &ldquo;opt-out&rdquo; by following the unsubscribe instructions provided in the e-mail you receive or by contacting us directly. Despite your indicated e-mail preferences, we may send you service related communication, including notices of any updates to our Terms of Use or Privacy Policy. </span></li>
              <li><strong>Access, Correction, and Deletion.</strong><span> Uiba allows individuals to access, modify, and set permissions with respect to End User Contact Data that it holds about them. For example, Uiba also provides certain features that allow you to publish and share some of your Personal Data, End User Contact Data or Completed Contact Data with others, but these features are totally optional and whether or not you use them is up to you. If you choose to connect your Uiba account with one of our development partners, you may be giving the partner access to your Personal Data, End User Contact Data or Completed Contact Data. We will tell you how the partner application will access your account and you can turn off access whenever you want. Finally, Uiba provides you with the ability to export your Personal Data, End User Contact Data or Completed Contact Data from our systems at any time using industry standard formats. </span></li>
              <li><strong>Additional Choices For California Residents &ndash; Your California Privacy Rights (As Provided by California Civil Code section 1798.83).</strong><span> California&rsquo;s &ldquo;Shine the Light&rdquo; law, Civil Code section 1798.83, requires certain businesses that share customer personal information with third parties for the third parties&rsquo; direct marketing purposes to respond to requests from California customers asking about the businesses&rsquo; practices related to such information-sharing. Alternately, such businesses may have in place a policy not to disclose a customer&rsquo;s personal information to third parties for the third parties&rsquo; direct marketing purposes if the customer has exercised an option to opt-out of such information-sharing. We have such a policy in place. As described in Section 8(2) above, you can opt-out of our sharing of your personal information with third parties for the third parties&rsquo; direct marketing purposes by claiming your profile and selecting how your personal information is used. To find out more about your opt-out rights, please contact us at the address listed in Section 13 below. Please note that under California law businesses are only required to respond to a customer making such a request once during any calendar year. </span></li>
            </ol>
            <li><strong>Data Integrity.</strong><span> Uiba will use Personal Data only in ways that are compatible with the purposes for which it was collected or subsequently authorized by you. Uiba will take reasonable steps to ensure that Personal Data is relevant to its intended use, accurate, complete, and current. Uiba depends on you to update and correct your Personal Data to the extent necessary for the purposes for which it was collected and subsequently authorized by you. </span></li>
            <li><strong>Enforcement.</strong><span> Uiba conducts periodic self-assessments to verify that the attestations and assertions it makes about its privacy practices are true and that such privacy practices have been implemented as presented. Uiba will take steps to remedy any problems arising out of failure to comply with the Privacy Shield principles. </span></li>
            <li><strong>Disputes.</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Generally.</strong><span> Uiba takes its users&rsquo; privacy concerns seriously. If you believe that Uiba has not adhered to this Privacy Policy, please contact Uiba as described in Section 13 below. In your email, please describe in as much detail as possible the ways in which you believe that this Privacy Policy has not been complied with. We will do our best to address your concerns. If you feel that your complaint has been addressed incompletely, we invite you to let us know for further investigation. </span></li>
              <li><strong>Dispute Resolution for Users Outside of the United States.</strong><span> If you are accessing this Website from the European Union, Asia, or any other region with laws or regulations governing personal data collection, use, and disclosure that differ from United States laws, please be advised that through your continued use of the Website, which is governed by U.S. law and this Privacy Policy as incorporated into our Terms of Service, you will be transferring your personal information into the United States and you consent to that transfer.</span></li>
            </ol>
            <li><strong>Security of Your Personal Data.</strong><span> Uiba is committed to protecting the security of your Personal Data. We use a variety of industry-standard security technologies and procedures to help protect your Personal Data from unauthorized access, use, or disclosure. We also require you to enter a password to access your account information. Please do not disclose your account password to unauthorized people. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while Uiba uses reasonable efforts to protect your Personal Data, Uiba cannot guarantee its absolute security. </span></li>
            <li><strong>Contact Information.</strong><span> Uiba welcomes your comments or questions regarding this Privacy Policy. or you need further assistance with respect to the access or use of the Website or Services, please contact us at the following email </span><span>address: support@uiba.co</span></li>
            <li><strong>Changes to This Privacy Policy.</strong><span> We may amend this Privacy Policy at any time at our sole discretion and without prior notice. If we make any material amendments, we will advise you about those changes by notifying you in a prominent place on our Website. You should check back with us from time to time in order to confirm that there have been no significant changes. Please note that the use of information that we gather is subject to the Privacy Policy then in effect at the time of use.</span></li>
          </ol>
<<<<<<< b92d05d3c3db46ac84a856f8d8e26e9867ad9176
          </Paper>
        </div>
        </MuiThemeProvider>
    )
  }
=======
          <li><strong>Security of Your Personal Data.</strong><span> Uiba is committed to protecting the security of your Personal Data. We use a variety of industry-standard security technologies and procedures to help protect your Personal Data from unauthorized access, use, or disclosure. We also require you to enter a password to access your account information. Please do not disclose your account password to unauthorized people. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while Uiba uses reasonable efforts to protect your Personal Data, Uiba cannot guarantee its absolute security. </span></li>
          <li><strong>Contact Information.</strong><span> Uiba welcomes your comments or questions regarding this Privacy Policy. or you need further assistance with respect to the access or use of the Website or Services, please contact us at the following email </span><span>address: support@uiba.co</span></li>
          <li><strong>Changes to This Privacy Policy.</strong><span> We may amend this Privacy Policy at any time at our sole discretion and without prior notice. If we make any material amendments, we will advise you about those changes by notifying you in a prominent place on our Website. You should check back with us from time to time in order to confirm that there have been no significant changes. Please note that the use of information that we gather is subject to the Privacy Policy then in effect at the time of use.</span></li>
        </ol>
        </Paper>
      </div>
  );
>>>>>>> company
};

export default Privacy;
