import React, { Component, PropTypes } from 'react';

import Paper from 'material-ui/Paper';
import { mixpanelURLTrack } from 'middlewares/mixpanelTrackers';

import lightBaseTheme from 'material-ui/styles/baseThemes/lightBaseTheme';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import classNames from 'classnames/bind';
import styles from 'css/components/terms';
const cx = classNames.bind(styles);

class Terms extends Component {

  componentDidMount() {
    mixpanelURLTrack('TERMS[load]:init');
  }

  render() {
    return (
      <div className={cx('terms') + ' container'}>
        <Paper className={cx('paper')} zDepth={2} >
          <p><strong>Uiba </strong><strong><br /></strong><strong>Terms of Use</strong></p>
          <p><span>These Terms of Use (</span><strong>&ldquo;Agreement&rdquo;</strong><span>) sets forth the legally binding terms for your use of the Uiba website (the "Website") and related services (the "Service"), and are an agreement between you and Uiba, Inc. (the Company, Website, and Service are collectively referenced as "we" or "us"). By accessing or using the Site or Services, you are accepting this Agreement (on behalf of yourself or the entity that you represent) and you represent and warrant that you have the right, authority, and capacity to enter into this Agreement (on behalf of yourself or the entity that you represent). You may not access or use the Site or Services or accept the Agreement if you are not at least 18 years old. If you do not agree with all of the provisions of this Agreement, do not access and/or use the Site or Services. </span></p>
          <ol className={cx('ordered-list')}>
            <li><strong>Account.</strong><span> In order to use certain features of the Site or Services (e.g., if you are a Developer), you must register for an account with Uiba (</span><strong>&ldquo;Account&rdquo;</strong><span>) and provide certain information about yourself as prompted by the registration form. In addition, you may voluntarily choose to create a Uiba Account. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information. You may delete your Account at any time, for any reason, by following the instructions on the Site. Uiba may suspend or terminate your Account in accordance with Section 9. You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account. You agree to immediately notify Uiba of any unauthorized use, or suspected unauthorized use of your Account or any other breach of security. Uiba cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements. </span></li>
            <li><strong>Licenses</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Site License.</strong><span> Subject to the terms of this Agreement, Uiba grants you a non-transferable, non-exclusive, license to use the Site for your personal, noncommercial use. </span></li>
              <li><strong>Uiba App License.</strong><span> If you are an End User, subject to the terms of this Agreement, Uiba grants you a non-transferable, non-exclusive, license to use the Uiba App for your personal, noncommercial use. </span></li>
              <li><strong>Completed Personal Data License.</strong><span> If you are an End Users, subject to the terms of this Agreement, Uiba grants you a non-transferable, non-exclusive, license to use the Completed Personal Data (defined below) you received through your use of a Uiba App or Developer App, for your personal, noncommercial use. </span></li>
              <li><strong>API License.</strong><span> If you are a Developer, please see the API License Addendum attached hereto and incorporated herein by this reference. </span></li>
              <li><strong>Certain Restrictions.</strong></li>
              <ol className={cx('ordered-list')}>
                <li><span>Except as set forth in the API License Addendum, the rights granted to you in this Agreement are subject to the following restrictions: (A) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site or Services; (B) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site or Services; (C) you shall not access the Site or Services in order to build a similar or competitive service; and (D) except as expressly stated herein, no part of the Site or Services may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Any future release, update, or other addition to functionality of the Site or Services shall be subject to the terms of this Agreement. All copyright and other proprietary notices on any Site or Services content must be retained on all copies thereof. </span></li>
                <li><span>You acknowledge and agree that: (A) Completed Contact Data has not been collected for, and is not intended to be indicative of, any person&rsquo;s employability, credit worthiness, credit standing, credit capacity, or other characteristics related to such person&rsquo;s manner or mode of living, as listed in Section 603(d) of the Fair Credit Reporting Act (</span><strong>&ldquo;FCRA&rdquo;</strong><span>), 15 USC Section 1681a; and (B) you shall not use any Completed Contact Data as a factor in establishing any person&rsquo;s eligibility for (1) credit or insurance used primarily for personal, family or household purposes, (2) employment purposes, or (3) other purposes authorized under Section 604 of the FCRA, 15 USC Section 1681b or any similar statute. </span></li>
                <li><span>You may not upload any debit or credit card information, bank account information, social security number, driver&rsquo;s license information, or government ID information. UIBA WILL NOT HAVE ANY OBLIGATION TO MAINTAIN THE CONFIDENTIALITY OR SECURITY OF SUCH INFORMATION. </span></li>
              </ol>
              <li><strong>Modification.</strong><span> Uiba reserves the right, at any time, to modify, suspend, or discontinue the Site or Services or any part thereof with or without notice. You agree that Uiba will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Site or Services or any part thereof. </span></li>
              <li><strong>No Support or Maintenance.</strong><span> You acknowledge and agree that Uiba will have no obligation to provide you with any support or maintenance in connection with the Site or Services. </span></li>
            </ol>
            <li><strong>End User Contact Data</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>End User Contact Data.</strong><span> If you are an End User, when you use a Site, a Uiba App or Developer App, we may collect End User Contact Data from you (as described in the Privacy Policy). If you are a Developer, when your End Users use your Developer App, we may collect End User Contact Data from your End Users. As used in this Agreement, </span><strong>&ldquo;your End User Contact Data&rdquo;</strong><span> means End User Contact Data we collect from you if you are an End User or End User Contact Data we collect from your End Users if you are a Developer. We may combine End User Contact Data with information we collect from third party sources to create Completed Contact Data (as defined in the Privacy Policy). You are solely responsible for your End User Contact Data. You hereby represent and warrant that your End User Contact Data, and providing us your End User Contact Data to use and disclose in accordance with our Privacy Policy, does not violate any third-party rights, including any privacy rights, or any laws, regulations, or obligations imposed by any third party. Uiba is not obligated to backup your End User Contact Data and your End User Contact Data may be deleted at any time. You are solely responsible for creating backup copies of your End User Contact Data if you desire. </span></li>
              <li><strong>License.</strong><span> You hereby grant, and you represent and warrant that you have the right to grant, to Uiba an irrevocable, perpetual, nonexclusive, royalty-free and fully paid, worldwide license to &ldquo;process&rdquo; (meaning to perform any activity, including reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, disclose, and otherwise use) your End User Contact Data, solely to the extent necessary to perform the Services in accordance with the Uiba Privacy Policy. </span></li>
              <li><strong>Enforcement.</strong><span> We reserve the right (but have no obligation) to review your End User Contact Data, investigate, and/or take appropriate action against you in our sole discretion if you violate this Agreement or otherwise create liability for us or any other person. Such acts may include removing or modifying your End User Contact Data, terminating your Account in accordance with Section 9, and/or reporting you to law enforcement authorities. </span></li>
            </ol>
            <li><strong>Ownership.</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>&ldquo;Intellectual Property Rights&rdquo;</strong><span> means all present and future worldwide copyrights, trademarks, trade secrets, patents, patent applications, mask work rights, moral rights, contract rights, and other proprietary rights recognized by the laws of any country. You acknowledge that the Site and Services (and all Intellectual Property Rights therein) are owned by Uiba or Uiba&rsquo;s licensors. Subject to Uiba&rsquo;s rights in the API, the Developer App (and all worldwide Intellectual Property Rights therein) are the exclusive property of Developer and its licensors. Uiba and its licensors reserve all rights not granted in this Agreement. Uiba does not license to Developer any rights to any Uiba trademark, trade name, or logo. The provision of the Site and Services does not transfer to you or any third party any rights, title or interest in or to any or all Intellectual Property Rights therein. </span></li>
              <li><span>If you provide Uiba any feedback or suggestions regarding the Site or Services (</span><strong>&ldquo;Feedback&rdquo;</strong><span>), you hereby assign to Uiba all rights in the Feedback and agree that Uiba shall have the right to use such Feedback and related information in any manner it deems appropriate. Uiba will treat any Feedback you provide to Uiba as non-confidential and non-proprietary. You agree that you will not submit to Uiba any information or ideas that you consider to be confidential or proprietary. </span></li>
            </ol>
            <li><strong>Indemnity.</strong><span> You agree to indemnify and hold Uiba (and its officers, employees, and agents) harmless, including costs and attorneys&rsquo; fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Site or Services, (b) your End User Contact Data, (c) your violation of this Agreement; (d) your violation of applicable laws or regulations (including any privacy laws), and (e) if you are a Developer, your Developer App. Uiba reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of Uiba. Uiba will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it. </span></li>
            <li><strong>Third Party Sites &amp; Ads; Developers</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Third Party Sites &amp; Ads.</strong><span> The Site might contain links to third party websites, services, and advertisements for third parties (collectively, &ldquo;Third Party Sites &amp; Ads&rdquo;). Such Third Party Sites &amp; Ads are not under the control of Uiba and Uiba is not responsible for any Third Party Sites &amp; Ads. Uiba provides these Third Party Sites &amp; Ads only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Sites &amp; Ads. You use all Third Party Sites &amp; Ads at your own risk. When you link to a Third Party Site &amp; Ad, the applicable third party&rsquo;s terms and policies apply, including the third party&rsquo;s privacy and data gathering practices. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third Party Sites &amp; Ads. </span></li>
              <li><strong>Developers.</strong><span> Each Developer is solely responsible for any and all of its Developer Apps. Because we do not control Developers or their Developer Apps, you acknowledge and agree that we are not responsible for any Developers or their Developer Apps and we make no guarantees regarding the accuracy, currency, suitability, or quality of any Developers or their Developer Apps, and we assume no responsibility for any Developers or their Developer Apps. Your interactions with Developers or their Developer Apps are solely between you and such Developer. You agree that Uiba will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Developer, we are under no obligation to become involved. </span></li>
              <li><strong>Release.</strong><span> You hereby release and forever discharge us (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or relates directly or indirectly to, any interactions with, or act or omission of, Developers, Developer Apps or Third Party Sites &amp; Ads. IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: &ldquo;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.&rdquo; </span></li>
            </ol>
            <li><strong>Disclaimers</strong></li>
          </ol>
          <p><span>THE SITE AND SERVICES (INCLUDING THE COMPANY APP, API, AND Completed Contact Data) ARE PROVIDED &ldquo;AS-IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; AND WE (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WE (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE SITE OR SERVICES (INCLUDING THE COMPANY APP, API, AND Completed Contact Data): (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE. </span></p>
          <p><span>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. </span></p>
          <ol className={cx('ordered-list')}>
            <li><strong>Limitation on Liability</strong></li>
          </ol>
          <p><span>IN NO EVENT SHALL WE (AND OUR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT OR YOUR USE OF, OR INABILITY TO USE, THE SITE OR SERVICES (INCLUDING THE COMPANY APP, API, AND Completed Contact Data), EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SITE AND SERVICES (INCLUDING THE COMPANY APP, API, AND Completed Contact Data) ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING THEREFROM. </span></p>
          <p><span>NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT, THE SITE, OR SERVICES (INCLUDING THE COMPANY APP, API, AND Completed Contact Data) (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU&rsquo;VE PAID COMPANY IN THE PRIOR 12 MONTHS (IF ANY). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT. YOU AGREE THAT OUR SUPPLIERS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT, THE SITE, OR SERVICES (INCLUDING THE COMPANY APP, API, AND Completed Contact Data). </span></p>
          <p><span>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. </span></p>
          <ol className={cx('ordered-list')}>
            <li><strong>Term and Termination.</strong><span> Subject to this Section, this Agreement will remain in full force and effect while you use the Site or Services. We may (a) suspend your rights to use the Site and/or Services (including your Account) or (b) terminate this Agreement, at any time for any reason at our sole discretion, including for any use of the Site or Services in violation of this Agreement. Upon termination of this Agreement, your Account and right to access and use the Site and Services will terminate immediately. Even after this Agreement is terminated, the following provisions of this Agreement will remain in effect: Sections 2.5 &ndash; 2.7, and 4&ndash;10. </span></li>
            <li><strong>General</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Changes to Terms of Use.</strong><span> This Agreement is subject to occasional revision, and if we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any) and/or by prominently posting notice of the changes on our Site. Any changes to this agreement will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on our Site. These changes will be effective immediately for new users of our Site or Services. You are responsible for providing us with your most current e-mail address. In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice. Continued use of our Site or Services following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes. </span></li>
              <li><strong>Arbitration Agreement And Jury Trial Waiver, Class Action Waiver, And Forum Selection Clause.</strong><span> All controversies, disputes, demands, counts, claims, or causes of action between you and Uiba arising out of, under, or related in any way to this Agreement or our privacy practices, shall exclusively be settled through binding arbitration. </span></li>
            </ol>
          </ol>
          <ol className={cx('ordered-list')}>
            <ol className={cx('ordered-list')}>
              <ol className={cx('ordered-list')}>
                <li><span>Arbitration shall be subject to the Federal Arbitration Act and not any state arbitration law. The arbitration shall be conducted before one commercial arbitrator with substantial experience in resolving commercial contract disputes from the American Arbitration Association (</span><strong>&ldquo;AAA&rdquo;</strong><span>). As modified by this Agreement, and unless agreed upon by the parties in writing, the arbitration will be governed by the AAA&rsquo;s Commercial Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer Related Disputes (collectively </span><strong>&ldquo;Rules and Procedures&rdquo;</strong><span>). </span></li>
                <li><span>You are thus GIVING UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract EXCEPT for matters that may be taken to small claims court. Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury. You are entitled to a FAIR HEARING, BUT the arbitration procedures are SIMPLER AND MORE LIMITED THAN RULES APPLICABLE IN COURT. Arbitrator decisions are as enforceable as any court order and are subject to VERY LIMITED REVIEW BY A COURT. </span></li>
                <li><span>You and Uiba must abide by the following rules: (a) for any claim that could otherwise be brought in small claims court, the arbitration shall be conducted solely based on written submissions and, if the arbitrator deems it appropriate, a telephonic hearing; (b) if the claim exceeds what can be recovered in a small claims court, the arbitration shall be conducted solely based on written submissions or a telephonic hearing, unless the arbitrator deems a face-to-face hearing is appropriate, in which case one should be held at a location agreed to by you and Uiba, and if the parties cannot agree on a location for the hearing, the arbitrator will determine a location for the proceedings which is reasonably convenient to both parties with due consideration of their ability to travel and other pertinent circumstances; (c) the arbitrator&rsquo;s ruling is binding and not merely advisory; (d) ANY CLAIMS BROUGHT BY YOU OR UIBA MUST BE BROUGHT IN THE PARTIES&rsquo; INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING; (e) THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON&rsquo;S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, (f) in the event that you are able to demonstrate that the costs of arbitration will be prohibitive as compared to costs of litigation, Uiba will pay as much of your filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive as compared to the cost of litigation, (g) Uiba also reserves the right in its sole and exclusive discretion to assume responsibility for all of the costs of the arbitration; (h) the arbitrator shall honor claims of privilege and privacy recognized at law; (i) a decision by the arbitrator (including any finding of fact and/or conclusion of law) against either you or Uiba shall be confidential unless otherwise required to be disclosed by law or by any administrative body and may not be collaterally used against either of them in existing or subsequent litigation or arbitration involving any other person/Uiba customer; and (j) each side pays its own attorneys&rsquo; fees and expenses unless there is a statutory provision that requires the prevailing party to be paid its fees&rsquo; and litigation expenses. </span></li>
                <li><span>Notwithstanding the foregoing, either you or Uiba may bring an individual action in small claims court. In addition, if you are a user outside of the United States, Section 11(b) of the Privacy Policy (Dispute Resolution for Users Outside of the United States), and not this arbitration provision, shall apply to any disputes related to privacy. Further, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party&rsquo;s patent, copyright, trademark, or trade secret shall not be subject to this arbitration provision. Such claims shall be exclusively brought (unless such courts do not have personal jurisdiction in the dispute) in the state courts located in Douglas County, Colorado or the federal courts located in Denver County, Colorado. Additionally, notwithstanding this arbitration provision, either party may seek emergency equitable relief before such courts in order to maintain the status quo pending the arbitrator&rsquo;s ruling, and hereby agree to submit to the personal jurisdiction of such courts. A request for interim measures shall not be deemed a waiver of the right to arbitrate. </span></li>
                <li><span>With the exception of subparts (d) and (e) in the paragraph above (prohibiting arbitration on a class or collective basis), if any part of this arbitration provision is deemed to be invalid, unenforceable or illegal, or otherwise conflicts with the Rules and Procedures, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting provision were not contained herein. If, however, either subpart (d) or (e) is found to be invalid, unenforceable or illegal, then the entirety of this arbitration provision shall be null and void, and neither You nor Uiba shall be entitled to arbitration. In the event this arbitration provision is held unenforceable by a court, or in the event AAA refuses to arbitrate the dispute, all controversies, disputes, demands, counts, claims, or causes of action between you and Uiba shall be exclusively brought in the state or federal courts specified in subsection &ldquo;(d)&rdquo; above. </span></li>
                <li><span>For more information on AAA, its Rules and Procedures, and how to file an arbitration claim, you may call AAA at 800-778-7879 or visit the AAA website at </span><a href="http://www.adr.org"><span>http://www.adr.org</span></a><span>. </span></li>
              </ol>
              <li><strong>Choice of Law.</strong><span> The Terms of Use is made under and shall be governed by and construed in accordance with the laws of the State of California, consistent with the Federal Arbitration Act, without giving effect to any principles that provide for the application of the law of another jurisdiction. </span></li>
              <li><strong>Entire Agreement.</strong><span> This Agreement constitutes the entire agreement between you and us regarding the use of the Site and Services. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision. The section titles in this Agreement are for convenience only and have no legal or contractual effect. The word including means including without limitation. If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Uiba will not be liable for any delay or non-performance of its obligations under this Agreement due to any cause beyond its control. Your relationship to Uiba is that of an independent contractor, and neither party is an agent or partner of the other. This Agreement, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Uiba&rsquo;s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The terms of this Agreement shall be binding upon assignees. There are no third party beneficiaries of this Agreement. </span></li>
              <li><strong>Copyright/Trademark Information.</strong><span> Copyright &copy; 2010-2014, Uiba Inc. All rights reserved. All trademarks, logos and service marks (</span><strong>&ldquo;Marks&rdquo;</strong><span>) displayed on the Site are our property or the property of other third parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party which may own the Marks. </span></li>
              <li><strong>Contact Information:</strong><span> In the event that you have any questions about these Terms of Service, or that you need further assistance with respect to the access or use of the Website or Services, please notify us at the following email address: </span><a href="mailto:support@Uiba.co"><span>support@Uiba.co</span></a></li>
            </ol>
          </ol>
          <p><strong><strong>&nbsp;</strong></strong></p>
          <p><strong>API License Addendum</strong></p>
          <p><span>This API License Addendum (</span><strong>&ldquo;Addendum&rdquo;</strong><span>) applies to Developers and is incorporated by reference into the Terms of Use (</span><strong>&ldquo;Agreement&rdquo;</strong><span>). </span></p>
          <ol className={cx('ordered-list')}>
            <li><strong>Definitions.</strong><span> As used in this Addendum: </span></li>
            <ol className={cx('ordered-list')}>
              <li><strong>&ldquo;API&rdquo;</strong><span> means the software program or programs in source code or executable code form, any documentation provided therewith, and any modified, updated, or enhanced versions of such items that Uiba provides to Developer pursuant to this Addendum. For the avoidance of doubt, the API is deemed part of the &ldquo;Service&rdquo; (as defined above). </span></li>
              <li><strong>&ldquo;API Key&rdquo;</strong><span> means the code provided by Uiba that permits Developer to access the API. </span></li>
              <li><strong>&ldquo;Developer App&rdquo;</strong><span> means a plug-in or other software application that is (i) developed by or for Developer to improve contact information through use of the Service and/or the API, and (ii) complies with the requirements of this Agreement and any restrictions described in the Uiba Privacy Policy. </span></li>
            </ol>
            <li><strong>License.</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Grant.</strong><span> Subject to the terms and conditions of this Addendum, Uiba grants to Developer a limited, non-exclusive, non-transferable, license to: (i) internally use the API Key to access the API, (ii) internally use, perform, display, reproduce the API solely as necessary to develop, maintain and support the Developer App, in accordance with the specifications included in the API; (iii) provided that the Developer App complies with all requirements in this Agreement, reproduce and distribute copies of the API (in its original form or as modified), in executable code form only, solely as incorporated into the Developer App to End Users pursuant to a binding written agreement that contains terms no less restrictive than the Minimum EULA Terms set forth below; and (iv) distribute Completed Contact Data through the Developer App to End Users. </span></li>
              <li><strong>Restrictions.</strong><span> Developer acknowledges that the API and its structure, organization, and source code constitute valuable trade secrets of Uiba and its suppliers. Accordingly, Developer agrees not to disclose, distribute, sublicense, lease, rent, loan, resell or otherwise transfer the data received from the Service or API, the Service or API (other than those elements incorporated into the Developer App) or the API Key to any third party. Developer must reproduce, on all copies made by or for Developer, and must not remove, alter, or obscure in any way all proprietary rights notices (including copyright notices) of Uiba or its suppliers on or within the copies of the API. Developer will immediately notify Uiba if Developer becomes aware of any material breach relating to the API. </span></li>
              <li><strong>Data Restrictions.</strong><span> Developer will not, and will require any and all third parties to which it provides any data from the Service or the API (</span><strong>&ldquo;Data Recipients&rdquo;</strong><span>) to not, use such data for the purposes of cookie tracking, ad exchanges, ad networks, data brokerages, sending electronic communications (including email) in violation of applicable law, or any other activity or purpose identified as prohibited by Uiba in any communication sent to Developer. If Uiba informs Developer that a specified activity or purpose is prohibited, Developer will ensure that any and all Data Recipients immediately cease processing of any such data for the prohibited activity or purpose. If Developer is not subject to the laws based on the EU Data Protection Directive 95/46 or Swiss Federal Data Protection law, Developer hereby agrees to either (i) subscribe to the Safe Harbor principles or (ii) contractually agree to provide at least the same level of protection for Personal Data as is required by the relevant Safe Harbor principles. </span><strong>Strict compliance with this section is a condition of the license in this Agreement and a material requirement of this Agreement.</strong></li>
            </ol>
            <li><strong>Developer Apps.</strong></li>
            <ol className={cx('ordered-list')}>
              <li><strong>Submission.</strong><span> If requested by Uiba, Developer will submit to Uiba each Developer App that Developer distributes or plans to distribute, in accordance with the instructions on Uiba&rsquo;s website. Developer grants to Uiba a non-exclusive license to internally use, perform, display, reproduce, modify, and create derivative works of the Developer App to evaluate the Developer App during the term of this Addendum. Uiba may, at any time and in its sole discretion, notify Developer that Developer may no longer distribute a Developer App until such Developer App meets conditions specified by Uiba. Upon receipt of such notice, Developer shall promptly cease distribution of the Developer App until the Developer App meets such conditions, in Uiba&rsquo;s judgment. </span></li>
              <li><strong>App Policy.</strong><span> Developer is solely responsible and liable for the Developer App. Developer is solely responsible for supporting the Developer App. The Developer App must comply with the following (the </span><strong>&ldquo;App Policy&rdquo;</strong><span>): the Developer App may not (i) violate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) violate any laws or regulations (including any privacy laws) or any obligations or restrictions imposed by any third party; (iii) be unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another&rsquo;s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, or patently offensive, or promote racism, bigotry, hatred, or physical harm of any kind against any group or individual, or be otherwise objectionable; (iv) be harmful to minors in any way; (v) contain any computer viruses, worms, or any software intended to damage or alter a computer system or data; (vi) send unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; or (vii) harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent. </span></li>
              <li><strong>Minimum EULA Terms.</strong><span> The following constitute the &ldquo;Minimum EULA Terms&rdquo;: (i) the End User must accept Uiba&rsquo;s Terms of Use and Privacy Policy; (ii) title to and ownership of the API remains with Uiba and its suppliers; (c) the End User may not (A) copy, alter or modify the API, (B) reverse engineer, decompile, disassemble, or in any way attempt to derive the source code for the API, or (C) use the API except as embedded within the Developer App; (iv) all express and implied warranties regarding the API by Uiba and its suppliers are disclaimed; (v) all consequential, special, and indirect damages are disclaimed on behalf of Uiba and its suppliers; (vi) the End User must grant the Developer all rights (including consents and licenses) needed from the End User for Developer to grant Uiba the license to use its End User Contact Data (as described in Section 3(a) of the Agreement); and (vii) Developer&rsquo;s privacy policy must comply with all applicable privacy laws and must contain a notice that Uiba will collect, and/or receive from Developer, End User Contact Data and will process such data in accordance with Uiba&rsquo;s privacy policy. </span></li>
            </ol>
            <li><strong>Confidentiality. &ldquo;Confidential Information&rdquo;</strong><span> includes the API Key and API and any other materials of Uiba that Uiba designates as confidential or which Developer should reasonably believe to be confidential, including Third Party Access Tokens, Account Credentials and Social Media User Ids. Developer shall hold Uiba&rsquo;s Confidential Information in confidence and shall neither disclose such Confidential Information to third parties nor use Uiba&rsquo;s Confidential Information for any purpose other than as necessary to perform under this Addendum. Developer agrees to limit access to the Confidential Information to those employees, agents, and representatives who are necessary for Developer to perform its obligations under this Addendum. All such employees, agents, and representatives must have a written confidentiality agreement with Developer that is no less restrictive than the terms contained herein. Developer will protect the Confidential Information from unauthorized use, access, or disclosure in the same manner as Developer protects its own confidential or proprietary information of a similar nature and with no less than reasonable care. The foregoing restrictions on disclosure shall not apply to Confidential Information that is (a) already known by Developer; (b) becomes, through no act or fault of Developer, publicly known; (c) received by Developer from a third party without a restriction on disclosure or use; or (d) independently developed by Developer without reference to Uiba&rsquo;s Confidential Information. To the extent Developer submits any Contact Information to Uiba via the API (</span><strong>&ldquo;Submitted Information&rdquo;</strong><span>), then: (i) as between Uiba and Developer, such Submitted Information shall belong to Developer, and Uiba will not claim any right, title or interest to such information; (ii) Uiba will not add Submitted Information to any of its database, except as necessary to provide services to Developer; and (iii) Submitted Information shall remain the Confidential Information of Developer, and will not be disclosed by Full Contact to any third party (including any other developer). Notwithstanding the foregoing, nothing herein shall restrict Uiba from (iv) using, accessing, processing, collecting, disclosing, sharing, or distributing any Contact Information that Uiba collects from publicly available sources via the Internet and social networks, including through their public or licensed API (</span><strong>&ldquo;Public Data&rdquo;</strong><span>), and (ii) providing, processing, or disclosing Public Information or any Contact Information that is provided by a third party to Uiba, even if such information or Public Data is duplicative of Submitted Information. </span></li>
            <li><strong>Fees.</strong><span> Developer will immediately pay all fees applicable to the products or services purchased from Uiba. The purchase path pages of the Site are hereby incorporated into this Addendum. </span></li>
            <li><strong>Term and Termination.</strong><span> This Addendum will remain in effect until the Developer&rsquo;s subscription has expired or it has been terminated as provided in this Section. Developer may terminate this Addendum, effective immediately upon written notice to Uiba, if Uiba breaches any provision of this Addendum and does not cure the breach within thirty (30) days after receiving written notice thereof. Uiba may terminate this Addendum, effective immediately upon written notice to Developer, if Developer breaches any provision of this Addendum. Either party may terminate this Addendum for convenience upon providing sixty (60) days notice to the other party. Upon termination or expiration of this Addendum for any reason, all licensed rights granted in this Addendum to Developer will immediately cease to exist and Developer will irrecoverably delete any and all data it received from the Service or the API. Sections 2.2, 2.3, and 4, as well as Developer&rsquo;s obligation to pay any fees applicable to the balance of the Developer&rsquo;s then-current subscription term, will survive any expiration or termination of this Addendum for any reason. </span></li>
          </ol>
          <p><strong>Trademark Information</strong></p>
          <p><span>The product and brand names referenced on this website are trademarks of their respective owners and do not imply affiliation with, sponsorship, or endorsement by owners.</span></p>

        </Paper>
      </div>
    );
  }
};

export default Terms;
