export const UPDATE_RANGE_AUTOFILL_SUCCESS = 'UPDATE_RANGE_AUTOFILL_SUCCESS'
export const UPDATE_ADDRESS_AUTOFILL_SUCCESS = 'UPDATE_ADDRESS_AUTOFILL_SUCCESS'
export const NEW_ADDRESS = 'NEW_ADDRESS';
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';
export const TOGGLE_ADDRESS_ADD = 'TOGGLE_ADDRESS_ADD';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';

export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE';

export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';
export const TOGGLE_ADDRESS_EDIT = 'TOGGLE_ADDRESS_EDIT';
export const SHOW_ADDRESS_EDIT_ICON = 'SHOW_ADDRESS_EDIT_ICON';
export const HIDE_ADDRESS_EDIT_ICON = 'HIDE_ADDRESS_EDIT_ICON';

export const CREATE_ADDRESS_ERROR_MSG = 'CREATE_ADDRESS_ERROR_MSG';
export const CLEAR_RANGE_ADDRESS = 'CLEAR_RANGE_ADDRESS';
export const SET_ZIP = 'SET_ZIP';
export const SET_RANGE = 'SET_RANGE';