export const GET_APPLICANT = 'GET_APPLICANT';
export const GET_APPLICANT_REQUEST = 'GET_APPLICANT_REQUEST';
export const GET_APPLICANT_SUCCESS = 'GET_APPLICANT_SUCCESS';
export const GET_APPLICANT_FAILURE = 'GET_APPLICANT_FAILURE';
export const GET_APPLICANTS = 'GET_APPLICANTS';
export const GET_APPLICANTS_REQUEST = 'GET_APPLICANTS_REQUEST';
export const GET_APPLICANTS_SUCCESS = 'GET_APPLICANTS_SUCCESS';
export const GET_APPLICANTS_FAILURE = 'GET_APPLICANTS_FAILURE';

export const TOGGLE_APPLICANT_FILTER_SKILL_ADD = 'TOGGLE_APPLICANT_FILTER_SKILL_ADD';
export const CHANGE_APPLICANT_FILTER_SKILL = 'CHANGE_APPLICANT_FILTER_SKILL';

export const NEW_APPLICANT_FILTER_SKILL = 'NEW_APPLICANT_FILTER_SKILL';
export const CHANGE_APPLICANT_FILTER_SKILLS = 'CHANGE_APPLICANT_FILTER_SKILLS';

export const UPDATE_APPLICANT_FILTERS = 'UPDATE_APPLICANT_FILTERS';

export const GET_APPLICANT_FILTER_SKILLS = 'GET_APPLICANT_FILTER_SKILLS';
export const GET_APPLICANT_FILTER_SKILLS_REQUEST = 'GET_APPLICANT_FILTER_SKILLS_REQUEST';
export const GET_APPLICANT_FILTER_SKILLS_SUCCESS = 'GET_APPLICANT_FILTER_SKILLS_SUCCESS';
export const GET_APPLICANT_FILTER_SKILLS_FAILURE = 'GET_APPLICANT_FILTER_SKILLS_FAILURE';

export const CREATE_APPLICANT_FILTER_SKILL = 'CREATE_APPLICANT_FILTER_SKILL';
export const CREATE_APPLICANT_FILTER_SKILL_REQUEST = 'CREATE_APPLICANT_FILTER_SKILL_REQUEST';
export const CREATE_APPLICANT_FILTER_SKILL_SUCCESS = 'CREATE_APPLICANT_FILTER_SKILL_SUCCESS';
export const CREATE_APPLICANT_FILTER_SKILL_FAILURE = 'CREATE_APPLICANT_FILTER_SKILL_FAILURE';

export const UPDATE_APPLICANT_FILTER_SKILL = 'UPDATE_APPLICANT_FILTER_SKILL';
export const UPDATE_APPLICANT_FILTER_SKILL_REQUEST = 'UPDATE_APPLICANT_FILTER_SKILL_REQUEST';
export const UPDATE_APPLICANT_FILTER_SKILL_SUCCESS = 'UPDATE_APPLICANT_FILTER_SKILL_SUCCESS';
export const UPDATE_APPLICANT_FILTER_SKILL_FAILURE = 'UPDATE_APPLICANT_FILTER_SKILL_FAILURE';

export const DELETE_APPLICANT_FILTER_SKILL = 'DELETE_APPLICANT_FILTER_SKILL';
export const DELETE_APPLICANT_FILTER_SKILL_REQUEST = 'DELETE_APPLICANT_FILTER_SKILL_REQUEST';
export const DELETE_APPLICANT_FILTER_SKILL_SUCCESS = 'DELETE_APPLICANT_FILTER_SKILL_SUCCESS';
export const DELETE_APPLICANT_FILTER_SKILL_FAILURE = 'DELETE_APPLICANT_FILTER_SKILL_FAILURE';

export const TOGGLE_APPLICANT_EDU_FILTER = 'TOGGLE_APPLICANT_EDU_FILTER';

export const APPLICANT_FILTER_CLEAR = 'APPLICANT_FILTER_CLEAR';
export const APPLICANT_FILTER_CHANGE = 'APPLICANT_FILTER_CHANGE';
export const APPLICANT_FILTER_REMOVE = 'APPLICANT_FILTER_REMOVE';