export const SET_COMPANY_FROM_TYPEAHEAD = 'SET_COMPANY_FROM_TYPEAHEAD';
export const UPDATE_COMPANY_TYPEAHEAD_SUCCESS = 'UPDATE_COMPANY_TYPEAHEAD_SUCCESS'
export const SET_INITIAL_COMPANY_SELECTION = 'SET_INITIAL_COMPANY_SELECTION'
export const UPDATE_COMPANY_SELECTION = 'UPDATE_COMPANY_SELECTION'

export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const NEW_COMPANY = 'NEW_COMPANY';
export const CHANGE_COMPANY = 'CHANGE_COMPANY';
export const CHANGE_COMPANYS = 'CHANGE_COMPANYS';
export const TOGGLE_COMPANY_ADD = 'TOGGLE_COMPANY_ADD';

export const CREATE_COMPANY = 'CREATE_COMPANY';
export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';

export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';

export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_COMPANY_REQUEST = 'DELETE_COMPANY_REQUEST';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAILURE = 'DELETE_COMPANY_FAILURE';
