export const TOGGLE_RESEND = 'TOGGLE_RESEND';
export const CHANGE_CONFIRM_EMAIL = 'CHANGE_CONFIRM_EMAIL';
export const RESEND_CONFIRM_SUCCESS = 'RESEND_CONFIRM_SUCCESS';
export const RESEND_CONFIRM_FAILURE = 'RESEND_CONFIRM_FAILURE';