export const NEW_FILTER = 'NEW_FILTER';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_FILTERS = 'CHANGE_FILTERS';

export const GET_FILTERS = 'GET_FILTERS';
export const GET_FILTERS_REQUEST = 'GET_FILTERS_REQUEST';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILURE = 'GET_FILTERS_FAILURE';

export const CREATE_FILTER = 'CREATE_FILTER';
export const CREATE_FILTER_REQUEST = 'CREATE_FILTER_REQUEST';
export const CREATE_FILTER_SUCCESS = 'CREATE_FILTER_SUCCESS';
export const CREATE_FILTER_FAILURE = 'CREATE_FILTER_FAILURE';

export const DELETE_FILTER = 'DELETE_FILTER';
export const DELETE_FILTER_REQUEST = 'DELETE_FILTER_REQUEST';
export const DELETE_FILTER_SUCCESS = 'DELETE_FILTER_SUCCESS';
export const DELETE_FILTER_FAILURE = 'DELETE_FILTER_FAILURE';