export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const CREATE_ERROR = 'CREATE_ERROR';


export const TOGGLE_APPLY = 'TOGGLE_APPLY';
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLY_FAILURE = 'APPLY_FAILURE';


export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';


export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';

export const TOGGLE_PROFILE_EDIT = 'TOGGLE_PROFILE_EDIT';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';


export const NEW_JOB = 'NEW_JOB';
export const CHANGE_JOB = 'CHANGE_JOB';
export const CHANGE_JOBS = 'CHANGE_JOBS';
export const TOGGLE_JOB_ADD = 'TOGGLE_JOB_ADD';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAILURE = 'UPDATE_JOB_FAILURE';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAILURE = 'DELETE_JOB_FAILURE';



export const NEW_SCHOOL = 'NEW_SCHOOL';
export const CHANGE_SCHOOL = 'CHANGE_SCHOOL';
export const CHANGE_SCHOOLS = 'CHANGE_SCHOOLS';
export const TOGGLE_SCHOOL_ADD = 'TOGGLE_SCHOOL_ADD';

export const GET_SCHOOLS = 'GET_SCHOOLS';
export const GET_SCHOOLS_REQUEST = 'GET_SCHOOLS_REQUEST';
export const GET_SCHOOLS_SUCCESS = 'GET_SCHOOLS_SUCCESS';
export const GET_SCHOOLS_FAILURE = 'GET_SCHOOLS_FAILURE';

export const CREATE_SCHOOL = 'CREATE_SCHOOL';
export const CREATE_SCHOOL_REQUEST = 'CREATE_SCHOOL_REQUEST';
export const CREATE_SCHOOL_SUCCESS = 'CREATE_SCHOOL_SUCCESS';
export const CREATE_SCHOOL_FAILURE = 'CREATE_SCHOOL_FAILURE';

export const UPDATE_SCHOOL = 'UPDATE_SCHOOL';
export const UPDATE_SCHOOL_REQUEST = 'UPDATE_SCHOOL_REQUEST';
export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';
export const UPDATE_SCHOOL_FAILURE = 'UPDATE_SCHOOL_FAILURE';

export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const DELETE_SCHOOL_REQUEST = 'DELETE_SCHOOL_REQUEST';
export const DELETE_SCHOOL_SUCCESS = 'DELETE_SCHOOL_SUCCESS';
export const DELETE_SCHOOL_FAILURE = 'DELETE_SCHOOL_FAILURE';



export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const UPDATE_RESULTS_SUCCESS = 'UPDATE_RESULTS_SUCCESS';
export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const SET_INITIAL_SELECTION = 'SET_INITIAL_SELECTION';

export const NEW_SKILL = 'NEW_SKILL';
export const CHANGE_SKILL = 'CHANGE_SKILL';
export const CHANGE_SKILLS = 'CHANGE_SKILLS';
export const TOGGLE_SKILL_ADD = 'TOGGLE_SKILL_ADD';

export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_REQUEST = 'GET_SKILLS_REQUEST';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAILURE = 'GET_SKILLS_FAILURE';

export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_SKILL_REQUEST = 'CREATE_SKILL_REQUEST';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const CREATE_SKILL_FAILURE = 'CREATE_SKILL_FAILURE';

export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILL_REQUEST = 'UPDATE_SKILL_REQUEST';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_FAILURE = 'UPDATE_SKILL_FAILURE';

export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SKILL_REQUEST = 'DELETE_SKILL_REQUEST';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAILURE = 'DELETE_SKILL_FAILURE';

export const NEW_LANGUAGE = 'NEW_LANGUAGE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_LANGUAGES = 'CHANGE_LANGUAGES';
export const TOGGLE_LANGUAGE_ADD = 'TOGGLE_LANGUAGE_ADD';

export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_LANGUAGES_REQUEST = 'GET_LANGUAGES_REQUEST';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILURE = 'GET_LANGUAGES_FAILURE';

export const CREATE_LANGUAGE = 'CREATE_LANGUAGE';
export const CREATE_LANGUAGE_REQUEST = 'CREATE_LANGUAGE_REQUEST';
export const CREATE_LANGUAGE_SUCCESS = 'CREATE_LANGUAGE_SUCCESS';
export const CREATE_LANGUAGE_FAILURE = 'CREATE_LANGUAGE_FAILURE';

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_LANGUAGE_REQUEST = 'UPDATE_LANGUAGE_REQUEST';
export const UPDATE_LANGUAGE_SUCCESS = 'UPDATE_LANGUAGE_SUCCESS';
export const UPDATE_LANGUAGE_FAILURE = 'UPDATE_LANGUAGE_FAILURE';

export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';
export const DELETE_LANGUAGE_REQUEST = 'DELETE_LANGUAGE_REQUEST';
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS';
export const DELETE_LANGUAGE_FAILURE = 'DELETE_LANGUAGE_FAILURE';


export const NEW_INTEREST = 'NEW_INTEREST';
export const CHANGE_INTEREST = 'CHANGE_INTEREST';
export const CHANGE_INTERESTS = 'CHANGE_INTERESTS';
export const TOGGLE_INTEREST_ADD = 'TOGGLE_INTEREST_ADD';

export const GET_INTERESTS = 'GET_INTERESTS';
export const GET_INTERESTS_REQUEST = 'GET_INTERESTS_REQUEST';
export const GET_INTERESTS_SUCCESS = 'GET_INTERESTS_SUCCESS';
export const GET_INTERESTS_FAILURE = 'GET_INTERESTS_FAILURE';

export const CREATE_INTEREST = 'CREATE_INTEREST';
export const CREATE_INTEREST_REQUEST = 'CREATE_INTEREST_REQUEST';
export const CREATE_INTEREST_SUCCESS = 'CREATE_INTEREST_SUCCESS';
export const CREATE_INTEREST_FAILURE = 'CREATE_INTEREST_FAILURE';

export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const UPDATE_INTEREST_REQUEST = 'UPDATE_INTEREST_REQUEST';
export const UPDATE_INTEREST_SUCCESS = 'UPDATE_INTEREST_SUCCESS';
export const UPDATE_INTEREST_FAILURE = 'UPDATE_INTEREST_FAILURE';

export const DELETE_INTEREST = 'DELETE_INTEREST';
export const DELETE_INTEREST_REQUEST = 'DELETE_INTEREST_REQUEST';
export const DELETE_INTEREST_SUCCESS = 'DELETE_INTEREST_SUCCESS';
export const DELETE_INTEREST_FAILURE = 'DELETE_INTEREST_FAILURE';



export const NEW_PROJECT = 'NEW_PROJECT';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CHANGE_PROJECTS = 'CHANGE_PROJECTS';
export const TOGGLE_PROJECT_ADD = 'TOGGLE_PROJECT_ADD';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';



export const TOGGLE_RESEND = 'TOGGLE_RESEND';
export const CHANGE_CONFIRM_EMAIL = 'CHANGE_CONFIRM_EMAIL';
export const RESEND_CONFIRM_SUCCESS = 'RESEND_CONFIRM_SUCCESS';
export const RESEND_CONFIRM_FAILURE = 'RESEND_CONFIRM_FAILURE';


export const SET_COMPANY_FROM_TYPEAHEAD = 'SET_COMPANY_FROM_TYPEAHEAD';
export const UPDATE_COMPANY_TYPEAHEAD_SUCCESS = 'UPDATE_COMPANY_TYPEAHEAD_SUCCESS'
export const SET_INITIAL_COMPANY_SELECTION = 'SET_INITIAL_COMPANY_SELECTION'
export const UPDATE_COMPANY_SELECTION = 'UPDATE_COMPANY_SELECTION'

export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const NEW_COMPANY = 'NEW_COMPANY';
export const CHANGE_COMPANY = 'CHANGE_COMPANY';
export const CHANGE_COMPANYS = 'CHANGE_COMPANYS';
export const TOGGLE_COMPANY_ADD = 'TOGGLE_COMPANY_ADD';

export const CREATE_COMPANY = 'CREATE_COMPANY';
export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';

export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';

export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_COMPANY_REQUEST = 'DELETE_COMPANY_REQUEST';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAILURE = 'DELETE_COMPANY_FAILURE';

export const UPDATE_RANGE_AUTOFILL_SUCCESS = 'UPDATE_RANGE_AUTOFILL_SUCCESS'
export const UPDATE_ADDRESS_AUTOFILL_SUCCESS = 'UPDATE_ADDRESS_AUTOFILL_SUCCESS'
export const NEW_ADDRESS = 'NEW_ADDRESS';
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';
export const TOGGLE_ADDRESS_ADD = 'TOGGLE_ADDRESS_ADD';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';

export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE';

export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';
export const TOGGLE_ADDRESS_EDIT = 'TOGGLE_ADDRESS_EDIT';
export const SHOW_ADDRESS_EDIT_ICON = 'SHOW_ADDRESS_EDIT_ICON';
export const HIDE_ADDRESS_EDIT_ICON = 'HIDE_ADDRESS_EDIT_ICON';

export const CLEAR_RANGE_ADDRESS = 'CLEAR_RANGE_ADDRESS';
export const SET_ZIP = 'SET_ZIP';
export const SET_RANGE = 'SET_RANGE';


export const NEW_ROLE = 'NEW_ROLE';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const CHANGE_ROLES = 'CHANGE_ROLES';
export const TOGGLE_ROLE_ADD = 'TOGGLE_ROLE_ADD';

export const GET_ROLE = 'GET_ROLE';
export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GET_ROLE_FAILURE';

export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILURE = 'CREATE_ROLE_FAILURE';

export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';

export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';

export const NEW_ROLE_SKILL = 'NEW_ROLE_SKILL';
export const CHANGE_ROLE_SKILL = 'CHANGE_ROLE_SKILL';
export const CHANGE_ROLE_SKILLS = 'CHANGE_ROLE_SKILLS';
export const TOGGLE_ROLE_SKILL_ADD = 'TOGGLE_ROLE_SKILL_ADD';

export const GET_ROLE_SKILLS = 'GET_ROLE_SKILLS';
export const GET_ROLE_SKILLS_REQUEST = 'GET_ROLE_SKILLS_REQUEST';
export const GET_ROLE_SKILLS_SUCCESS = 'GET_ROLE_SKILLS_SUCCESS';
export const GET_ROLE_SKILLS_FAILURE = 'GET_ROLE_SKILLS_FAILURE';

export const CREATE_ROLE_SKILL = 'CREATE_ROLE_SKILL';
export const CREATE_ROLE_SKILL_REQUEST = 'CREATE_ROLE_SKILL_REQUEST';
export const CREATE_ROLE_SKILL_SUCCESS = 'CREATE_ROLE_SKILL_SUCCESS';
export const CREATE_ROLE_SKILL_FAILURE = 'CREATE_ROLE_SKILL_FAILURE';

export const UPDATE_ROLE_SKILL = 'UPDATE_ROLE_SKILL';
export const UPDATE_ROLE_SKILL_REQUEST = 'UPDATE_ROLE_SKILL_REQUEST';
export const UPDATE_ROLE_SKILL_SUCCESS = 'UPDATE_ROLE_SKILL_SUCCESS';
export const UPDATE_ROLE_SKILL_FAILURE = 'UPDATE_ROLE_SKILL_FAILURE';

export const DELETE_ROLE_SKILL = 'DELETE_ROLE_SKILL';
export const DELETE_ROLE_SKILL_REQUEST = 'DELETE_ROLE_SKILL_REQUEST';
export const DELETE_ROLE_SKILL_SUCCESS = 'DELETE_ROLE_SKILL_SUCCESS';
export const DELETE_ROLE_SKILL_FAILURE = 'DELETE_ROLE_SKILL_FAILURE';

export const TOGGLE_ROLE_EDU_REQUIREMENT = 'TOGGLE_ROLE_EDU_REQUIREMENT';

export const GET_APPLICANT = 'GET_APPLICANT';
export const GET_APPLICANT_REQUEST = 'GET_APPLICANT_REQUEST';
export const GET_APPLICANT_SUCCESS = 'GET_APPLICANT_SUCCESS';
export const GET_APPLICANT_FAILURE = 'GET_APPLICANT_FAILURE';
export const GET_APPLICANTS = 'GET_APPLICANTS';
export const GET_APPLICANTS_REQUEST = 'GET_APPLICANTS_REQUEST';
export const GET_APPLICANTS_SUCCESS = 'GET_APPLICANTS_SUCCESS';
export const GET_APPLICANTS_FAILURE = 'GET_APPLICANTS_FAILURE';

export const TOGGLE_APPLICANT_FILTER_SKILL_ADD = 'TOGGLE_APPLICANT_FILTER_SKILL_ADD';
export const CHANGE_APPLICANT_FILTER_SKILL = 'CHANGE_APPLICANT_FILTER_SKILL';
export const CREATE_APPLICANT_FILTER_SKIL = 'CREATE_APPLICANT_FILTER_SKIL';
export const UPDATE_APPLICANT_FILTER_SKIL = 'UPDATE_APPLICANT_FILTER_SKIL';
export const DELETE_APPLICANT_FILTER_SKIL = 'DELETE_APPLICANT_FILTER_SKIL';

export const NEW_APPLICANT_FILTER_SKILL = 'NEW_APPLICANT_FILTER_SKILL';
export const CHANGE_APPLICANT_FILTER_SKILLS = 'CHANGE_APPLICANT_FILTER_SKILLS';

export const GET_APPLICANT_FILTER_SKILLS = 'GET_APPLICANT_FILTER_SKILLS';
export const GET_APPLICANT_FILTER_SKILLS_REQUEST = 'GET_APPLICANT_FILTER_SKILLS_REQUEST';
export const GET_APPLICANT_FILTER_SKILLS_SUCCESS = 'GET_APPLICANT_FILTER_SKILLS_SUCCESS';
export const GET_APPLICANT_FILTER_SKILLS_FAILURE = 'GET_APPLICANT_FILTER_SKILLS_FAILURE';

export const CREATE_APPLICANT_FILTER_SKILL = 'CREATE_APPLICANT_FILTER_SKILL';
export const CREATE_APPLICANT_FILTER_SKILL_REQUEST = 'CREATE_APPLICANT_FILTER_SKILL_REQUEST';
export const CREATE_APPLICANT_FILTER_SKILL_SUCCESS = 'CREATE_APPLICANT_FILTER_SKILL_SUCCESS';
export const CREATE_APPLICANT_FILTER_SKILL_FAILURE = 'CREATE_APPLICANT_FILTER_SKILL_FAILURE';

export const UPDATE_APPLICANT_FILTER_SKILL = 'UPDATE_APPLICANT_FILTER_SKILL';
export const UPDATE_APPLICANT_FILTER_SKILL_REQUEST = 'UPDATE_APPLICANT_FILTER_SKILL_REQUEST';
export const UPDATE_APPLICANT_FILTER_SKILL_SUCCESS = 'UPDATE_APPLICANT_FILTER_SKILL_SUCCESS';
export const UPDATE_APPLICANT_FILTER_SKILL_FAILURE = 'UPDATE_APPLICANT_FILTER_SKILL_FAILURE';

export const DELETE_APPLICANT_FILTER_SKILL = 'DELETE_APPLICANT_FILTER_SKILL';
export const DELETE_APPLICANT_FILTER_SKILL_REQUEST = 'DELETE_APPLICANT_FILTER_SKILL_REQUEST';
export const DELETE_APPLICANT_FILTER_SKILL_SUCCESS = 'DELETE_APPLICANT_FILTER_SKILL_SUCCESS';
export const DELETE_APPLICANT_FILTER_SKILL_FAILURE = 'DELETE_APPLICANT_FILTER_SKILL_FAILURE';

export const TOGGLE_APPLICANT_EDU_FILTER = 'TOGGLE_APPLICANT_EDU_FILTER';

export const APPLICANT_FILTER_CLEAR = 'APPLICANT_FILTER_CLEAR';
export const APPLICANT_FILTER_CHANGE = 'APPLICANT_FILTER_CHANGE';
export const APPLICANT_FILTER_REMOVE = 'APPLICANT_FILTER_REMOVE';

export const FETCH_APPLICANTS_FILTER_SKILLS = 'FETCH_APPLICANTS_FILTER_SKILLS';
export const FETCH_APPLICANTS_FILTER_SKILLS_SUCCESS = 'FETCH_APPLICANTS_FILTER_SKILLS_SUCCESS';
export const FETCH_APPLICANTS_FILTER_SKILLS_FAILURE = 'FETCH_APPLICANTS_FILTER_SKILLS_FAILURE';

export const GET_SCORES_REQUEST = 'GET_SCORES_REQUEST';
export const GET_SCORES_SUCCESS = 'GET_SCORES_SUCCESS';
export const GET_SCORES_FAILURE = 'GET_SCORES_FAILURE';
export const CLEAR_SCORES = 'CLEAR_SCORES';

