export const NEW_INTEREST = 'NEW_INTEREST';
export const CHANGE_INTEREST = 'CHANGE_INTEREST';
export const CHANGE_INTERESTS = 'CHANGE_INTERESTS';
export const TOGGLE_INTEREST_ADD = 'TOGGLE_INTEREST_ADD';

export const GET_INTERESTS = 'GET_INTERESTS';
export const GET_INTERESTS_REQUEST = 'GET_INTERESTS_REQUEST';
export const GET_INTERESTS_SUCCESS = 'GET_INTERESTS_SUCCESS';
export const GET_INTERESTS_FAILURE = 'GET_INTERESTS_FAILURE';

export const CREATE_INTEREST = 'CREATE_INTEREST';
export const CREATE_INTEREST_REQUEST = 'CREATE_INTEREST_REQUEST';
export const CREATE_INTEREST_SUCCESS = 'CREATE_INTEREST_SUCCESS';
export const CREATE_INTEREST_FAILURE = 'CREATE_INTEREST_FAILURE';

export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const UPDATE_INTEREST_REQUEST = 'UPDATE_INTEREST_REQUEST';
export const UPDATE_INTEREST_SUCCESS = 'UPDATE_INTEREST_SUCCESS';
export const UPDATE_INTEREST_FAILURE = 'UPDATE_INTEREST_FAILURE';

export const DELETE_INTEREST = 'DELETE_INTEREST';
export const DELETE_INTEREST_REQUEST = 'DELETE_INTEREST_REQUEST';
export const DELETE_INTEREST_SUCCESS = 'DELETE_INTEREST_SUCCESS';
export const DELETE_INTEREST_FAILURE = 'DELETE_INTEREST_FAILURE';

export const DISMISS_INTEREST_MESSAGE = 'DISMISS_INTEREST_MESSAGE';

