export const NEW_LANGUAGE = 'NEW_LANGUAGE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_LANGUAGES = 'CHANGE_LANGUAGES';
export const TOGGLE_LANGUAGE_ADD = 'TOGGLE_LANGUAGE_ADD';
export const TOGGLE_LANGUAGE_EDIT = 'TOGGLE_LANGUAGE_EDIT';

export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_LANGUAGES_REQUEST = 'GET_LANGUAGES_REQUEST';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILURE = 'GET_LANGUAGES_FAILURE';

export const CREATE_LANGUAGE = 'CREATE_LANGUAGE';
export const CREATE_LANGUAGE_REQUEST = 'CREATE_LANGUAGE_REQUEST';
export const CREATE_LANGUAGE_SUCCESS = 'CREATE_LANGUAGE_SUCCESS';
export const CREATE_LANGUAGE_FAILURE = 'CREATE_LANGUAGE_FAILURE';

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_LANGUAGE_REQUEST = 'UPDATE_LANGUAGE_REQUEST';
export const UPDATE_LANGUAGE_SUCCESS = 'UPDATE_LANGUAGE_SUCCESS';
export const UPDATE_LANGUAGE_FAILURE = 'UPDATE_LANGUAGE_FAILURE';

export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';
export const DELETE_LANGUAGE_REQUEST = 'DELETE_LANGUAGE_REQUEST';
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS';
export const DELETE_LANGUAGE_FAILURE = 'DELETE_LANGUAGE_FAILURE';

export const DISMISS_LANGUAGE_MESSAGE = 'DISMISS_LANGUAGE_MESSAGE';
