export const NEW_ROLE = 'NEW_ROLE';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const CHANGE_ROLES = 'CHANGE_ROLES';
export const TOGGLE_ROLE_ADD = 'TOGGLE_ROLE_ADD';
export const TOGGLE_ROLE_EDIT = 'TOGGLE_ROLE_EDIT';
export const CHANGE_ROLE_EDIT = 'CHANGE_ROLE_EDIT';

export const GET_ROLE = 'GET_ROLE';
export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GET_ROLE_FAILURE';

export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILURE = 'CREATE_ROLE_FAILURE';

export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';

export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';

export const NEW_ROLE_SKILL = 'NEW_ROLE_SKILL';
export const CHANGE_ROLE_SKILL = 'CHANGE_ROLE_SKILL';
export const CHANGE_ROLE_SKILLS = 'CHANGE_ROLE_SKILLS';
export const TOGGLE_ROLE_SKILL_ADD = 'TOGGLE_ROLE_SKILL_ADD';
export const TOGGLE_ROLE_SKILL_EDIT_ADD = 'TOGGLE_ROLE_SKILL_EDIT_ADD';

export const GET_ROLE_SKILLS = 'GET_ROLE_SKILLS';
export const GET_ROLE_SKILLS_REQUEST = 'GET_ROLE_SKILLS_REQUEST';
export const GET_ROLE_SKILLS_SUCCESS = 'GET_ROLE_SKILLS_SUCCESS';
export const GET_ROLE_SKILLS_FAILURE = 'GET_ROLE_SKILLS_FAILURE';

export const CREATE_ROLE_SKILL = 'CREATE_ROLE_SKILL';
export const CREATE_ROLE_SKILL_REQUEST = 'CREATE_ROLE_SKILL_REQUEST';
export const CREATE_ROLE_SKILL_SUCCESS = 'CREATE_ROLE_SKILL_SUCCESS';
export const CREATE_ROLE_SKILL_FAILURE = 'CREATE_ROLE_SKILL_FAILURE';

export const UPDATE_ROLE_SKILL = 'UPDATE_ROLE_SKILL';
export const UPDATE_ROLE_SKILL_REQUEST = 'UPDATE_ROLE_SKILL_REQUEST';
export const UPDATE_ROLE_SKILL_SUCCESS = 'UPDATE_ROLE_SKILL_SUCCESS';
export const UPDATE_ROLE_SKILL_FAILURE = 'UPDATE_ROLE_SKILL_FAILURE';

export const DELETE_ROLE_SKILL = 'DELETE_ROLE_SKILL';
export const DELETE_ROLE_SKILL_REQUEST = 'DELETE_ROLE_SKILL_REQUEST';
export const DELETE_ROLE_SKILL_SUCCESS = 'DELETE_ROLE_SKILL_SUCCESS';
export const DELETE_ROLE_SKILL_FAILURE = 'DELETE_ROLE_SKILL_FAILURE';

export const FETCH_ROLE_SKILLS = 'FETCH_ROLE_SKILLS';
export const FETCH_ROLE_SKILLS_SUCCESS = 'FETCH_ROLE_SKILLS_SUCCESS';
export const FETCH_ROLE_SKILLS_FAILURE = 'FETCH_ROLE_SKILLS_FAILURE';

export const EDIT_ROLE_SKILL = 'EDIT_ROLE_SKILL';
export const CREATE_EDIT_ROLE_SKILL = 'CREATE_EDIT_ROLE_SKILL';
export const DELETE_EDIT_ROLE_SKILL = 'DELETE_EDIT_ROLE_SKILL';
export const UPDATE_EDIT_ROLE_SKILL = 'UPDATE_EDIT_ROLE_SKILL';
export const CHANGE_EDIT_ROLE_SKILLS = 'CHANGE_EDIT_ROLE_SKILLS';

export const TOGGLE_ROLE_EDU_REQUIREMENT = 'TOGGLE_ROLE_EDU_REQUIREMENT';
