export const NEW_SCHOOL = 'NEW_SCHOOL';
export const CHANGE_SCHOOL = 'CHANGE_SCHOOL';
export const CHANGE_SCHOOLS = 'CHANGE_SCHOOLS';
export const TOGGLE_SCHOOL_ADD = 'TOGGLE_SCHOOL_ADD';

export const GET_SCHOOLS = 'GET_SCHOOLS';
export const GET_SCHOOLS_REQUEST = 'GET_SCHOOLS_REQUEST';
export const GET_SCHOOLS_SUCCESS = 'GET_SCHOOLS_SUCCESS';
export const GET_SCHOOLS_FAILURE = 'GET_SCHOOLS_FAILURE';

export const CREATE_SCHOOL = 'CREATE_SCHOOL';
export const CREATE_SCHOOL_REQUEST = 'CREATE_SCHOOL_REQUEST';
export const CREATE_SCHOOL_SUCCESS = 'CREATE_SCHOOL_SUCCESS';
export const CREATE_SCHOOL_FAILURE = 'CREATE_SCHOOL_FAILURE';

export const UPDATE_SCHOOL = 'UPDATE_SCHOOL';
export const UPDATE_SCHOOL_REQUEST = 'UPDATE_SCHOOL_REQUEST';
export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';
export const UPDATE_SCHOOL_FAILURE = 'UPDATE_SCHOOL_FAILURE';

export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const DELETE_SCHOOL_REQUEST = 'DELETE_SCHOOL_REQUEST';
export const DELETE_SCHOOL_SUCCESS = 'DELETE_SCHOOL_SUCCESS';
export const DELETE_SCHOOL_FAILURE = 'DELETE_SCHOOL_FAILURE';

