export const GET_SCORES_REQUEST = 'GET_SCORES_REQUEST';
export const GET_SCORES_SUCCESS = 'GET_SCORES_SUCCESS';
export const GET_SCORES_FAILURE = 'GET_SCORES_FAILURE';
export const CLEAR_SCORES = 'CLEAR_SCORES';
export const SYNC_SCORES_SUCCESS = 'SYNC_SCORES_SUCCESS';
export const SYNC_SCORES_FAILURE = 'SYNC_SCORES_FAILURE';