export const NEW_SKILL = 'NEW_SKILL';
export const CHANGE_SKILL = 'CHANGE_SKILL';
export const CHANGE_SKILLS = 'CHANGE_SKILLS';
export const TOGGLE_SKILL_ADD = 'TOGGLE_SKILL_ADD';

export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_REQUEST = 'GET_SKILLS_REQUEST';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAILURE = 'GET_SKILLS_FAILURE';

export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_SKILL_REQUEST = 'CREATE_SKILL_REQUEST';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const CREATE_SKILL_FAILURE = 'CREATE_SKILL_FAILURE';

export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILL_REQUEST = 'UPDATE_SKILL_REQUEST';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_FAILURE = 'UPDATE_SKILL_FAILURE';

export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SKILL_REQUEST = 'DELETE_SKILL_REQUEST';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAILURE = 'DELETE_SKILL_FAILURE';

export const TOGGLE_SKILL_INPUT_FOCUS = 'TOGGLE_SKILL_INPUT_FOCUS';
export const DISMISS_LANGUAGE_MESSAGE = 'DISMISS_LANGUAGE_MESSAGE';

