export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const UPDATE_RESULTS_SUCCESS = 'UPDATE_RESULTS_SUCCESS';
export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const SET_INITIAL_SELECTION = 'SET_INITIAL_SELECTION';